package nvc.guide.modules.nvcpractice.model;

public enum NvcAgentScene {
    SCENARIO_GENERATOR,
    DIALOGUE_GUIDE,
    DIFFICULT_PARTNER,
    STEP_OBSERVE_COACH,
    STEP_FEELING_COACH,
    STEP_NEED_COACH,
    STEP_REQUEST_COACH,
    NVC_EXPRESSION_EVALUATOR,
    EMPATHY_COACH,
    NVC_KNOWLEDGE_ADVISOR,
    PROFILE_ANALYZER
}
